# Generated by Django 4.1.2 on 2022-10-30 10:56

from django.db import migrations, models
import utils.image


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.image.file_upload),
        ),
    ]
