# Generated by Django 4.1 on 2022-10-05 22:06

from django.db import migrations, models
import django.db.models.manager
import utils.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=2000)),
                ('phone', models.CharField(blank=True, max_length=2000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=utils.image.file_upload)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-id',),
                'permissions': [('change_post_status', 'Can change the status of posts')],
            },
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
