# Generated by Django 4.1.2 on 2022-10-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_posts_dislikes_posts_likes_posts_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='views',
        ),
    ]
