# Generated by Django 4.1.2 on 2022-10-29 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_remove_posts_dislikes_remove_posts_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislikes',
            field=models.ManyToManyField(null=True, related_name='dislike_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.ManyToManyField(null=True, related_name='view_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
