# Generated by Django 4.1.2 on 2022-10-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rename_comments_comment_content_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_at']},
        ),
    ]
