# Generated by Django 4.1.3 on 2022-11-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='test_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
