# Generated by Django 4.1.3 on 2022-11-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_posts_test_count'),
    ]

    operations = [
    ]
