# Generated by Django 4.1 on 2022-10-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('type', models.CharField(choices=[('D', 'Developer'), ('M', 'Manager')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerEmployee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxy_app.employee',),
        ),
    ]
