# Generated by Django 4.1.3 on 2022-11-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
