# Generated by Django 4.1 on 2022-10-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCookieCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('change_session_cookie_cache_status', 'Can change the status of session-cookie-cache'),),
                'managed': False,
            },
        ),
    ]
